# Generated by Django 4.2.16 on 2026-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_library_project_user_revocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryfile',
            name='library_tasks',
            field=models.ManyToManyField(blank=True, help_text='后台任务挂载的文件，与项目为多对多；分配后同步写入项目关联', related_name='library_files', through='core.LibraryFileTask', to='core.librarytask', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='role',
            name='perm_assign_tasks',
            field=models.BooleanField(default=False, help_text='创建文件库任务、关联项目任务、向 App 用户分配任务', verbose_name='分配文件库任务'),
        ),
    ]
