# Generated by Django 4.2.16 on 2026-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_role_perm_htmlpdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("super_admin", "超级管理员"),
                    ("admin", "普通管理员"),
                    ("app_user", "App 用户"),
                    ("template_tester", "模板与 HTMLPDF 测试"),
                ],
                max_length=50,
                unique=True,
                verbose_name="角色代码",
            ),
        ),
    ]
