# Generated by Django 4.2.16 on 2026-05-12 01:06

from django.db import migrations, models


def _app_side_perm_defaults():
    return {
        "perm_manage_users": False,
        "perm_manage_roles": False,
        "perm_manage_menus": False,
        "perm_file_library": True,
        "perm_file_upload": True,
        "perm_file_upload_attachment": True,
        "perm_file_download": True,
        "perm_file_preview": True,
        "perm_file_delete": False,
        "perm_file_scope_own_only": True,
        "perm_process_pipeline": False,
        "perm_htmlpdf": False,
        "perm_assign_tasks": False,
        "perm_biz_registry": True,
    }


def _template_editor_perm_defaults():
    return {
        "perm_manage_users": False,
        "perm_manage_roles": False,
        "perm_manage_menus": False,
        "perm_file_library": True,
        "perm_file_upload": True,
        "perm_file_upload_attachment": False,
        "perm_file_download": True,
        "perm_file_preview": True,
        "perm_file_delete": False,
        "perm_file_scope_own_only": False,
        "perm_process_pipeline": False,
        "perm_htmlpdf": True,
        "perm_assign_tasks": True,
        "perm_biz_registry": False,
    }


def seed_template_editor_and_signatory_perms(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    te = _template_editor_perm_defaults()
    obj, created = Role.objects.get_or_create(
        code="template_editor",
        defaults={
            "name": "模板编辑",
            "description": "模板文件上传、HTMLPDF、任务模板新建与模板绑定",
            **te,
        },
    )
    if not created:
        obj.name = "模板编辑"
        obj.description = "模板文件上传、HTMLPDF、任务模板新建与模板绑定"
        for k, v in te.items():
            setattr(obj, k, v)
        obj.save()

    app_side = _app_side_perm_defaults()
    keys = list(app_side.keys())
    merged = {k: bool(app_side[k]) or bool(te[k]) for k in keys}
    merged["perm_file_delete"] = True
    merged["perm_process_pipeline"] = True
    merged["perm_file_scope_own_only"] = True

    sig = Role.objects.filter(code="authorized_signatory").first()
    if sig is not None:
        for k, v in merged.items():
            setattr(sig, k, v)
        sig.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_workflow_roles_and_case_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryfile',
            name='library_tasks',
            field=models.ManyToManyField(blank=True, help_text='仅「模板」类应挂任务模板；其它分类请通过项目关联。模板在任务挂到项目时可同步到项目。', related_name='library_files', through='core.LibraryFileTask', to='core.librarytask', verbose_name='关联任务模板'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('app_user', 'App 用户（兼容旧版，等同检测侧参与人）'), ('field_inspector', '检测员'), ('site_reviewer', '校核员'), ('report_author', '编制人'), ('report_auditor', '审核人'), ('authorized_signatory', '授权签字人'), ('template_editor', '模板编辑'), ('template_tester', '模板与 HTMLPDF 测试')], max_length=50, unique=True, verbose_name='角色代码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='perm_assign_tasks',
            field=models.BooleanField(default=False, help_text='创建任务模板、维护模板绑定、关联项目任务、向 App 用户分配任务', verbose_name='分配文件库任务'),
        ),
        migrations.RunPython(seed_template_editor_and_signatory_perms, noop_reverse),
    ]
