# Generated by Django — 创建检测项目权限（与 perm_assign_tasks 分离）

from django.db import migrations, models


def forwards_set_create_project_defaults(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    codes_true = {
        "super_admin",
        "admin",
        "app_user",
        "field_inspector",
        "site_reviewer",
        "report_author",
        "report_auditor",
        "authorized_signatory",
        "template_editor",
        "template_tester",
    }
    for r in Role.objects.all():
        if r.code in codes_true:
            r.perm_create_library_project = True
            r.save(update_fields=["perm_create_library_project"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_audit_signatory_all_projects_file_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="perm_create_library_project",
            field=models.BooleanField(
                default=False,
                help_text="在项目工作台新建检测项目；不含向他人分配任务",
                verbose_name="创建检测项目",
            ),
        ),
        migrations.RunPython(forwards_set_create_project_defaults, migrations.RunPython.noop),
    ]
