# Generated by Django 4.2.16 on 2026-07-17 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0061_case_report_signature_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('hospital', '医院信息'), ('project', '委托项目')], db_index=True, max_length=16, verbose_name='范围')),
                ('action', models.CharField(choices=[('create', '添加'), ('update', '编辑'), ('delete', '删除'), ('dispatch', '派工'), ('bind', '绑定'), ('unbind', '解绑'), ('other', '其他')], db_index=True, max_length=16, verbose_name='操作类型')),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='对象类型')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象 ID')),
                ('summary', models.CharField(max_length=512, verbose_name='操作摘要')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '业务操作日志',
                'verbose_name_plural': '业务操作日志',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='commissionorgequipment',
            options={'ordering': ['department_id', 'device_type', 'instance_no', 'sort_order', 'id'], 'verbose_name': '委托单位设备', 'verbose_name_plural': '委托单位设备'},
        ),
        migrations.RenameIndex(
            model_name='casereportsignaturerecord',
            new_name='core_casere_case_id_8200ab_idx',
            old_name='core_caserep_case_task_sa',
        ),
        migrations.RenameIndex(
            model_name='casereportsignaturerecord',
            new_name='core_casere_project_c04066_idx',
            old_name='core_caserep_proj_signed',
        ),
        migrations.RenameIndex(
            model_name='librarytasktemplatebindinghistory',
            new_name='core_librar_library_2437f5_idx',
            old_name='core_libtas_library_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='usersignature',
            new_name='core_usersi_user_id_225032_idx',
            old_name='core_usersig_user_upd',
        ),
        migrations.RenameIndex(
            model_name='usersignatureevent',
            new_name='core_usersi_user_id_6a0b64_idx',
            old_name='core_usersigev_user_created',
        ),
        migrations.RenameIndex(
            model_name='usersignatureevent',
            new_name='core_usersi_user_id_d17c02_idx',
            old_name='core_usersigev_user_type_cr',
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='device_type',
            field=models.CharField(blank=True, default='', help_text='与任务模板库「设备类型」文件夹对应（如 01 CT、02DR），匹配时忽略前导序号', max_length=128, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='instance_no',
            field=models.PositiveIntegerField(default=1, help_text='同一科室、同一设备类型下的序号，展示为设备1、设备2…', verbose_name='同类型台次'),
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='report_file',
            field=models.ForeignKey(blank=True, help_text='该科室下属项目中已生成并归入文件库「报告」分类的成品文件（最近一次）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_org_equipments', to='core.libraryfile', verbose_name='单台设备报告'),
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='report_task_bindings',
            field=models.JSONField(blank=True, default=list, help_text='如 [{"inspection_type":"验收检测","report_task_id":1}]；未配置时使用默认 report_task', verbose_name='检测类型与报告模板'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='checkout_project',
            field=models.ForeignKey(blank=True, help_text='展示用；实际关联以 checkout_project_ids 为准，可多项目/委托共用。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_instruments', to='core.libraryproject', verbose_name='最近出库项目'),
        ),
        migrations.AlterField(
            model_name='libraryproject',
            name='assigned_instrument_ids',
            field=models.JSONField(blank=True, default=dict, help_text='人员派工时为项目确定的具体仪器编号：{"shareMode":"per_task","qualityControl":[id,...],"radiationProtection":[id,...],"byTask":{"任务id":{...}}}。任务模板仅绑种类时不含编号。', verbose_name='已分配检测仪器'),
        ),
        migrations.AlterField(
            model_name='libraryproject',
            name='commission_organization',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 commission_org.name 同步，便于检索与历史兼容', max_length=255, verbose_name='委托单位名称'),
        ),
        migrations.AlterField(
            model_name='libraryprojectequipment',
            name='inspection_type',
            field=models.CharField(blank=True, default='', help_text='本次委托该设备执行的检测类型（如验收检测、状态检测），对应设备主数据 report_task_bindings', max_length=64, verbose_name='本次检测类型'),
        ),
        migrations.AlterField(
            model_name='librarytask',
            name='bound_instrument_ids',
            field=models.JSONField(blank=True, default=dict, help_text='JSON：bindingMode=kinds 时仅存仪器种类（name/model），具体编号在项目派工时写入 LibraryProject.assigned_instrument_ids。兼容旧版直接绑主键 id。', verbose_name='模板默认检测仪器'),
        ),
        migrations.AddField(
            model_name='bizoperationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biz_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='bizoperationlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biz_operation_logs', to='core.commissionorganization', verbose_name='关联机构'),
        ),
        migrations.AddField(
            model_name='bizoperationlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biz_operation_logs', to='core.libraryproject', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='bizoperationlog',
            index=models.Index(fields=['scope', '-created_at'], name='core_bizope_scope_bc59dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bizoperationlog',
            index=models.Index(fields=['organization', '-created_at'], name='core_bizope_organiz_b5dab8_idx'),
        ),
        migrations.AddIndex(
            model_name='bizoperationlog',
            index=models.Index(fields=['project', '-created_at'], name='core_bizope_project_7979c4_idx'),
        ),
    ]
