# Generated by Django 4.2.16 on 2026-07-21 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_org_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    try:
        from apps.core.org_roles import ORG_ROLE_SEED
    except Exception:
        return
    for code, meta in ORG_ROLE_SEED.items():
        perms = dict(meta["perms"])
        role, created = Role.objects.get_or_create(
            code=code,
            defaults={
                "name": meta["name"],
                "description": meta["description"],
                **perms,
            },
        )
        if not created:
            for k, v in perms.items():
                setattr(role, k, v)
            role.name = meta["name"]
            role.description = meta["description"]
            role.save()


def unseed_org_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    Role.objects.filter(
        code__in=[
            "admin_office",
            "dept_director_inspection",
            "dept_staff_inspection",
            "dept_director_evaluation",
            "dept_staff_evaluation",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0062_biz_operation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryproject',
            name='business_line',
            field=models.CharField(choices=[('inspection', '检测报告'), ('pre_eval', '预评价报告'), ('control_effect', '控制效果评价')], db_index=True, default='inspection', help_text='inspection=检测；pre_eval/control_effect 本期预留', max_length=32, verbose_name='业务线'),
        ),
        migrations.AddField(
            model_name='libraryproject',
            name='owning_org_unit',
            field=models.CharField(blank=True, db_index=True, default='', help_text='admin_office / inspection / evaluation；行政提交到部门后写入', max_length=32, verbose_name='接收部门'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_unit',
            field=models.CharField(blank=True, db_index=True, default='', help_text='结构化：admin_office / inspection / evaluation；新业务线角色使用', max_length=32, verbose_name='组织部门'),
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='department',
            field=models.ForeignKey(help_text='可挂在医院、院区或科室节点下；未选科室时挂在当前浏览的医院/院区。', on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='core.commissionorganization', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='commissionorgequipment',
            name='instance_no',
            field=models.PositiveIntegerField(default=1, help_text='同一挂载节点、同一设备类型下的序号，展示为设备1、设备2…', verbose_name='同类型台次'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('app_user', 'App 用户（兼容旧版，等同检测侧参与人）'), ('field_inspector', '检测员'), ('site_reviewer', '校核员'), ('report_author', '编制人'), ('report_auditor', '审核人'), ('authorized_signatory', '授权签字人'), ('template_editor', '模板编辑'), ('template_tester', '模板编辑器（测试）'), ('commission_coordinator', '委托统筹'), ('admin_office', '行政'), ('dept_director_inspection', '检测部主管'), ('dept_staff_inspection', '检测部员工'), ('dept_director_evaluation', '评价部主管'), ('dept_staff_evaluation', '评价部员工')], max_length=50, unique=True, verbose_name='角色代码'),
        ),
        migrations.CreateModel(
            name='UserInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='令牌')),
                ('org_unit', models.CharField(db_index=True, max_length=32, verbose_name='组织部门')),
                ('staff_role_code', models.CharField(db_index=True, help_text='一般为 dept_staff_inspection / dept_staff_evaluation', max_length=50, verbose_name='注册后角色代码')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite_tokens_created', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '用户邀请令牌',
                'verbose_name_plural': '用户邀请令牌',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_org_roles, unseed_org_roles),
    ]
