# Generated by Django 4.2.16 on 2026-07-29 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0063_org_roles_invite_and_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='挂载时快照标准价格，可按单笔调整', max_digits=12, verbose_name='成交单价')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_project_products_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '委托销售产品',
                'verbose_name_plural': '委托销售产品',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '销售产品分类',
                'verbose_name_plural': '销售产品分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='产品线名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '销售产品线',
                'verbose_name_plural': '销售产品线',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='bizoperationlog',
            name='scope',
            field=models.CharField(choices=[('hospital', '医院信息'), ('project', '委托项目'), ('product', '产品管理')], db_index=True, max_length=16, verbose_name='范围'),
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='产品名称')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标准价格')),
                ('unit', models.CharField(blank=True, default='', max_length=32, verbose_name='单位')),
                ('status', models.CharField(choices=[('listed', '已上架'), ('unlisted', '已下架')], db_index=True, default='listed', max_length=16, verbose_name='上下架')),
                ('owner_name', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('specs', models.TextField(blank=True, default='', verbose_name='规格属性')),
                ('default_device_types', models.JSONField(blank=True, default=list, help_text='如 ["CT","DR"]，与医院设备类型一致', verbose_name='默认设备类型')),
                ('default_inspection_types', models.JSONField(blank=True, default=list, help_text='如 ["验收检测","状态检测"]', verbose_name='默认检测类型')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.salesproductcategory', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_products_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.salesproductline', verbose_name='产品线')),
            ],
            options={
                'verbose_name': '销售产品',
                'verbose_name_plural': '销售产品',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LibraryProjectProductEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(blank=True, default='', max_length=64, verbose_name='检测类型')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='core.commissionorgequipment', verbose_name='受检设备')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='core.libraryprojectproduct', verbose_name='委托产品')),
            ],
            options={
                'verbose_name': '委托产品设备',
                'verbose_name_plural': '委托产品设备',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='libraryprojectproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_links', to='core.salesproduct', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='libraryprojectproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_products', to='core.libraryproject', verbose_name='所属委托'),
        ),
        migrations.AddConstraint(
            model_name='libraryprojectproductequipment',
            constraint=models.UniqueConstraint(fields=('project_product', 'equipment', 'inspection_type'), name='uniq_project_product_equipment_inspection'),
        ),
    ]
