# Generated by Django 4.2.16 on 2026-07-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_sales_product_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='default_device_counts',
            field=models.JSONField(blank=True, default=dict, help_text='如 {"CT": 2, "DR": 1}；未写的类型按 1 台计', verbose_name='各设备类型台数'),
        ),
        migrations.AddField(
            model_name='salesproduct',
            name='listed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='最近一次设为已上架的时间；新建且上架时写入', null=True, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='default_device_types',
            field=models.JSONField(blank=True, default=list, help_text='如 ["CT","DR"]，可多选；与医院设备类型一致', verbose_name='默认设备类型'),
        ),
    ]
