# Generated by Django 4.2.16 on 2026-08-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_allow_multi_same_type_project_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("super_admin", "超级管理员"),
                    ("admin", "普通管理员"),
                    ("app_user", "App 用户（兼容旧版，等同检测侧参与人）"),
                    ("field_inspector", "检测员"),
                    ("site_reviewer", "校核员"),
                    ("report_author", "编制人"),
                    ("report_auditor", "审核人"),
                    ("authorized_signatory", "授权签字人"),
                    ("template_editor", "模板编辑"),
                    ("template_tester", "模板编辑器（测试）"),
                    ("commission_coordinator", "委托统筹"),
                    ("admin_office", "行政"),
                    ("dept_director_inspection", "检测部主任"),
                    ("dept_staff_inspection", "检测部员工"),
                    ("dept_director_evaluation", "评价部主任"),
                    ("dept_staff_evaluation", "评价部员工"),
                ],
                max_length=50,
                unique=True,
                verbose_name="角色代码",
            ),
        ),
    ]
