# Generated by Django 4.2.16 on 2026-08-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_rename_dept_director_主管_to_主任"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitetoken",
            name="org_unit",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=32,
                verbose_name="组织部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinvitetoken",
            name="staff_role_code",
            field=models.CharField(
                db_index=True,
                help_text="注册成功后写入用户资料的角色 code",
                max_length=50,
                verbose_name="注册后角色代码",
            ),
        ),
    ]
