# Generated by Django 4.2.16 on 2026-08-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_role_perm_f1_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereportsignaturerecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='重新导出等场景作废签字链；非空表示本条不再计入有效签字状态。', null=True, verbose_name='作废时间'),
        ),
        migrations.AlterField(
            model_name='casereportsignaturerecord',
            name='report_file',
            field=models.ForeignKey(blank=True, help_text='指向任务的当前报告（原地覆盖）；签发定稿为另存快照，不挂在此字段。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_signature_records', to='core.libraryfile', verbose_name='叠印后报告'),
        ),
    ]
