# Generated by Django 4.2.16 on 2026-08-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_case_report_signature_voided_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
