# Generated by Django 4.2.16 on 2026-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_evaluation_report_embed"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="casereportsignaturerecord",
            new_name="core_casere_case_id_d87e8e_idx",
            old_name="core_casere_case_id_export_slot_idx",
        ),
        migrations.AddField(
            model_name="casereportsignaturerecord",
            name="task_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="稳定任务键",
            ),
        ),
        migrations.AddField(
            model_name="inspectioncase",
            name="task_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="新检测任务使用的稳定归属键；历史案件保留为空。",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="稳定任务键",
            ),
        ),
        migrations.AddField(
            model_name="inspectionsubmission",
            name="task_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="新检测任务使用的稳定归属键；历史提交保留为空。",
                max_length=128,
                null=True,
                unique=True,
                verbose_name="稳定任务键",
            ),
        ),
    ]
