# Generated by Django 4.2.16 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0074_rename_core_casere_case_id_export_slot_idx_core_casere_case_id_d87e8e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryocrprocesstask",
            name="task_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="新检测任务的 OCR 结果归属键；历史项目级 OCR 任务保留为空。",
                max_length=128,
                null=True,
                verbose_name="稳定任务键",
            ),
        ),
    ]
