# Generated by Django 4.2.16 on 2026-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_libraryocrprocesstask_task_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersignatureevent",
            name="task_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="稳定任务键",
            ),
        ),
    ]
